server:
  port: 8080
spring:
 thymeleaf:
  cache: false
  servlet:
   content-type: text/html
  enabled: true
  encoding: UTF-8
  mode: HTML5
  prefix: classpath:/templates/
  suffix: .html
 datasource:
  username: root
  password: root
  url: jdbc:mysql://localhost:3306/mybatistest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  driver-class-name: com.mysql.cj.jdbc.Driver
 redis:
   host: 192.168.1.252
   port: 6379
#   timeout: 3
#   jedis:
#     pool:
#       max-wait: 3
# Mybatis 设置
 resources:
   static-locations: classpath:/static/
   add-mappings: true
   cache:
     period: 3600
   chain:
     cache: true
     enabled: true
     compressed: false
     html-application-cache: true

mybatis:
 configuration:
##   是否开启自动驼峰命名规则(camel case)映射
  map-underscore-to-camel-case: true
## mapper映射xml文件的锁在路径
 mapper-locations:  classpath:mybatis-mapper/*/*Mapper.xml
# 对应实体类的路径
 typeAliasesPackage: com.imooc.miaosha.*.model
mapper:
  mappers:
    - tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL
#showSql
logging:
  level:
    com:
      example:
        mapper : debug

